sonar.projectKey=AhmadMayyaleh122_stores-apps
sonar.organization=ahmadmayyaleh122

sonar.sources=backend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,backend/generated/**,**/generated/**,**/*.generated.*
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.sourceEncoding=UTF-8

