export enum TenantProvisioningErrorCode {
  IDENTIFIER_INVALID = 'TENANT_IDENTIFIER_INVALID',
  DATABASE_URL_INVALID = 'TENANT_DATABASE_URL_INVALID',
  CONFIGURATION_INVALID = 'TENANT_PROVISIONING_CONFIGURATION_INVALID',
  ENCRYPTION_KEY_INVALID = 'TENANT_ENCRYPTION_KEY_INVALID',
  CREDENTIAL_ENCRYPTION_FAILED = 'TENANT_CREDENTIAL_ENCRYPTION_FAILED',
  CREDENTIAL_DECRYPTION_FAILED = 'TENANT_CREDENTIAL_DECRYPTION_FAILED',
  POSTGRES_ADMIN_UNAVAILABLE = 'POSTGRES_ADMIN_UNAVAILABLE',
  ROLE_CONFLICT = 'TENANT_ROLE_CONFLICT',
  ROLE_PROVISIONING_FAILED = 'TENANT_ROLE_PROVISIONING_FAILED',
  DATABASE_OWNER_CONFLICT = 'TENANT_DATABASE_OWNER_CONFLICT',
  DATABASE_PROVISIONING_FAILED = 'TENANT_DATABASE_PROVISIONING_FAILED',
  MIGRATION_FAILED = 'TENANT_MIGRATION_FAILED',
  IDENTITY_MISMATCH = 'TENANT_IDENTITY_MISMATCH',
  IDENTITY_INITIALIZATION_FAILED = 'TENANT_IDENTITY_INITIALIZATION_FAILED',
  VERIFICATION_FAILED = 'TENANT_VERIFICATION_FAILED',
  IDENTITY_CLEANUP_FAILED = 'TENANT_IDENTITY_CLEANUP_FAILED',
}

export class TenantProvisioningError extends Error {
  constructor(
    readonly code: TenantProvisioningErrorCode,
    message: string,
  ) {
    super(message);
    this.name = 'TenantProvisioningError';
  }
}
